apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tjiycc1fx-go 
  janus-idp.io/tekton: tjiycc1fx-go
  backstage.io/kubernetes-id: tjiycc1fx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tjiycc1fx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  