apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tjiycc1fx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tjiycc1fx-go 
  name: tjiycc1fx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tjiycc1fx-go 
